/**
 * scripts/build.js
 *
 * Converts docs/*.md files into the pages array embedded in dist/brewdocs.js.
 *
 * Usage:
 *   npm run build
 *
 * How it works:
 *   1. Reads docs/manifest.json — the ordered list of pages with their
 *      file path, page id, label, and sidebar section.
 *   2. For each entry, reads the corresponding Markdown file and converts
 *      it to HTML using `marked`.
 *   3. Post-processes links:
 *        - Relative .md links  → #page-id  with class="int-link"
 *        - External https/http → kept as-is with class="ext-link"
 *   4. Writes the generated pages array back into dist/brewdocs.js,
 *      replacing the block between the PAGES_START / PAGES_END markers.
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname, join, posix } from 'path';
import { fileURLToPath } from 'url';
import { Marked } from 'marked';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT      = resolve(__dirname, '..');
const DOCS_DIR  = join(ROOT, 'docs');
const DIST_JS   = join(ROOT, 'dist', 'brewdocs.js');

// ── 1. Load manifest ──────────────────────────────────────────────────────────
const manifest = JSON.parse(readFileSync(join(DOCS_DIR, 'manifest.json'), 'utf8'));

// Build a normalised path → page-id lookup (always forward slashes)
const fileToId = {};
for (const entry of manifest) {
  fileToId[entry.file.replace(/\\/g, '/')] = entry.id;
}

// ── 2. Link resolver ──────────────────────────────────────────────────────────
/**
 * Given an href and the source file path (relative to docs/), returns
 * the resolved href and whether it is external / internal.
 *
 * @param {string} href        Raw href from the Markdown link
 * @param {string} sourceFile  Path of the source .md file relative to docs/
 * @returns {{ href: string, cls: string|null }}
 */
function resolveHref(href, sourceFile) {
  // External links
  if (/^https?:\/\//.test(href) || href.startsWith('mailto:')) {
    return { href, cls: 'ext-link' };
  }

  // Pure anchor links — leave as-is
  if (href.startsWith('#')) {
    return { href, cls: null };
  }

  // Relative .md path — resolve to a page id
  const sourceDir = posix.dirname(sourceFile.replace(/\\/g, '/'));

  let mdPath = href;
  let anchor = '';

  // Split off any trailing anchor
  const hashIdx = mdPath.indexOf('#');
  if (hashIdx !== -1) {
    anchor  = mdPath.slice(hashIdx);   // e.g. "#section-id"
    mdPath  = mdPath.slice(0, hashIdx);
  }

  // Resolve relative to the source file's directory, normalise to forward slashes
  const resolved = posix.normalize(posix.join(sourceDir, mdPath));

  const pageId = fileToId[resolved];
  if (pageId) {
    return { href: '#' + pageId + anchor, cls: 'int-link' };
  }

  // Unrecognised relative path — keep unchanged
  return { href, cls: null };
}

// ── 3. Per-file marked instance ───────────────────────────────────────────────
/**
 * Returns a marked parse function configured with a custom link renderer
 * that resolves links relative to the given source file.
 *
 * @param {string} sourceFile  Path of the source .md file relative to docs/
 * @returns {function(string): string}
 */
function makeParser(sourceFile) {
  const instance = new Marked();

  instance.use({
    renderer: {
      link({ href, title, tokens }) {
        const text     = this.parser.parseInline(tokens);
        const resolved = resolveHref(href, sourceFile);
        let tag = `<a href="${resolved.href}"`;
        if (resolved.cls) tag += ` class="${resolved.cls}"`;
        if (title)        tag += ` title="${title}"`;
        tag += `>${text}</a>`;
        return tag;
      },
    },
  });

  return (markdown) => instance.parse(markdown);
}

// ── 4. Convert every page ─────────────────────────────────────────────────────
const pages = manifest.map((entry) => {
  const filePath = join(DOCS_DIR, entry.file);
  const markdown = readFileSync(filePath, 'utf8');
  const parse    = makeParser(entry.file);
  const html     = parse(markdown).trimEnd();

  return { id: entry.id, label: entry.label, section: entry.section, html };
});

// ── 5. Serialise to JS ────────────────────────────────────────────────────────
function jsString(str) {
  // Produce a single-quoted JS string literal, escaping as needed
  return "'" + str
    .replace(/\\/g,  "\\\\")
    .replace(/'/g,   "\\'")
    .replace(/\r/g,  "\\r")
    .replace(/\n/g,  "\\n")
    + "'";
}

const pagesBlock = [
  '  // PAGES_START — generated by scripts/build.js — do not edit by hand',
  '  var pages = [',
  pages.map((p) => [
    '    {',
    `      id: ${jsString(p.id)},`,
    `      label: ${jsString(p.label)},`,
    `      section: ${jsString(p.section)},`,
    `      html: ${jsString(p.html)},`,
    '    }',
  ].join('\n')).join(',\n'),
  '  ];',
  '  // PAGES_END',
].join('\n');

// ── 6. Patch dist/brewdocs.js ─────────────────────────────────────────────────
const existingJs = readFileSync(DIST_JS, 'utf8');

// Replace between PAGES_START … PAGES_END markers if they exist …
const markerRe = /[ \t]*\/\/ PAGES_START[\s\S]*?\/\/ PAGES_END/;

// … or fall back to replacing the hand-written pages array block
// (bounded by the "1. WIKI CONTENT" and "2. SPATIAL NAVIGATION" comment banners)
const legacyRe  = /(\/\/ ─+\n  \/\/ 1\. WIKI CONTENT[\s\S]*?\n)([\s\S]*?)(  \/\/ ─+\n  \/\/ 2\. SPATIAL NAVIGATION)/;

let updatedJs;
if (markerRe.test(existingJs)) {
  updatedJs = existingJs.replace(markerRe, pagesBlock);
} else if (legacyRe.test(existingJs)) {
  updatedJs = existingJs.replace(legacyRe, (_, before, _content, after) => {
    return before + pagesBlock + '\n\n  ' + after.trimStart();
  });
} else {
  console.error('ERROR: Could not locate the pages array in dist/brewdocs.js');
  process.exit(1);
}

writeFileSync(DIST_JS, updatedJs, 'utf8');
console.log(`✓ dist/brewdocs.js updated — ${pages.length} pages generated from docs/`);
